# Merge Census Data years 2021 and 2011 and calculate the Delta between them.

## 1. Load both years

In [21]:
#Libraries and Settings
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows',10)

In [22]:
#Data File to Dataframe
file='/Users/c32/Documents/NYCDSA/Projects/DATA/Ready_Data/1_Load_Census_2011.csv'
c11=pd.read_csv(file, converters={'zip': str})
print(c11.shape)
c11.head()

(33120, 44)

,zip,total_pop,male_pop,female_pop,male_ratio,female_ratio,age_under5_pop,age_5to9_pop,age_10to14_pop,age_15to19_pop,age_20to24_pop,age_25to34_pop,age_35to44_pop,age_45to54_pop,age_55to59_pop,age_60to64_pop,age_65to74_pop,age_75to84_pop,age_85andOver_pop,age_under5_ratio,age_5to9_ratio,age_10to14_ratio,age_15to19_ratio,age_20to24_ratio,age_25to34_ratio,age_35to44_ratio,age_45to54_ratio,age_55to59_ratio,age_60to64_ratio,age_65to74_ratio,age_75to84_ratio,age_85andOver_ratio,age_group_outlier,race_one,race_two_or_more,race_hispanic_or_latino,race_white_alone,race_black_or_african,race_american_indian_and_alaska_native,race_asian,race_native_hawaian_and_other_pacific_islander,race_some_other_race_alone,race_two_or_more_races,total_housing_units
0,00601,18533,8971,9562,0.484055,0.515945,1187,1083,1655,1569,1315,2427,2337,2396,1058,1140,1395,664,307,0.064048,0.058436,0.089300,0.084660,0.070955,0.130956,0.126099,0.129283,0.057087,0.061512,0.075271,0.035828,0.016565,True,18521,12,18360,150,0,0,0,0,23,0,6503
1,00602,41930,20568,21362,0.490532,0.509468,2381,2695,3013,3334,3075,5499,5642,6079,2576,2527,3167,1425,517,0.056785,0.064274,0.071858,0.079513,0.073337,0.131147,0.134558,0.144980,0.061436,0.060267,0.075531,0.033985,0.012330,False,39158,2772,39205,2393,49,17,0,0,38,228,16336
2,00603,54475,26588,27887,0.488077,0.511923,3360,3468,3658,3838,3715,6924,7220,6948,3275,3694,5033,2572,770,0.061680,0.063662,0.067150,0.070454,0.068196,0.127104,0.132538,0.127545,0.060119,0.067811,0.092391,0.047214,0.014135,True,51892,2583,52570,1372,8,0,123,0,152,250,23245
3,00606,6386,3085,3301,0.483088,0.516912,393,495,478,487,495,741,931,861,467,279,438,206,115,0.061541,0.077513,0.074851,0.076261,0.077513,0.116035,0.145788,0.134826,0.073129,0.043689,0.068588,0.032258,0.018008,False,6386,0,6368,0,18,0,0,0,0,0,2373
4,00610,29111,14162,14949,0.486483,0.513517,1657,1866,2162,2248,1876,3769,4066,3867,1815,1710,2554,1105,416,0.056920,0.064099,0.074267,0.077222,0.064443,0.129470,0.139672,0.132836,0.062348,0.058741,0.087733,0.037958,0.014290,False,28381,730,28782,268,20,0,0,0,35,6,11308

In [23]:
#Data File to Dataframe
file='/Users/c32/Documents/NYCDSA/Projects/DATA/Ready_Data/1_Load_Census_2021.csv'
c21=pd.read_csv(file, converters={'zip': str})
print(c21.shape)
c21.head()

(33774, 44)

,zip,total_pop,male_pop,female_pop,male_ratio,female_ratio,age_under5_pop,age_5to9_pop,age_10to14_pop,age_15to19_pop,age_20to24_pop,age_25to34_pop,age_35to44_pop,age_45to54_pop,age_55to59_pop,age_60to64_pop,age_65to74_pop,age_75to84_pop,age_85andOver_pop,age_under5_ratio,age_5to9_ratio,age_10to14_ratio,age_15to19_ratio,age_20to24_ratio,age_25to34_ratio,age_35to44_ratio,age_45to54_ratio,age_55to59_ratio,age_60to64_ratio,age_65to74_ratio,age_75to84_ratio,age_85andOver_ratio,age_group_outlier,race_one,race_two_or_more,race_hispanic_or_latino,race_white_alone,race_black_or_african,race_american_indian_and_alaska_native,race_asian,race_native_hawaian_and_other_pacific_islander,race_some_other_race_alone,race_two_or_more_races,total_housing_units
0,00601,17126,8451,8675,0.493460,0.506540,643,811,1166,1016,1054,2122,1967,2350,1237,1282,1986,1088,404,0.037545,0.047355,0.068084,0.059325,0.061544,0.123905,0.114855,0.137218,0.072229,0.074857,0.115964,0.063529,0.023590,True,16238,888,17038,88,0,0,0,0,0,0,7306
1,00602,37895,18588,19307,0.490513,0.509487,1267,1671,2154,2259,2406,4742,4680,5082,2736,3130,4605,2349,814,0.033434,0.044096,0.056841,0.059612,0.063491,0.125135,0.123499,0.134107,0.072199,0.082597,0.121520,0.061987,0.021480,True,25490,12405,35649,1770,1,44,19,0,80,332,17311
2,00603,49136,23817,25319,0.484716,0.515284,1873,2037,3099,3196,2998,5908,5962,6312,3259,3467,6225,3774,1026,0.038119,0.041456,0.063070,0.065044,0.061014,0.120238,0.121337,0.128460,0.066326,0.070559,0.126689,0.076807,0.020881,True,45386,3750,48121,731,19,0,38,0,84,143,24771
3,00606,5751,2817,2934,0.489828,0.510172,223,259,312,361,388,650,691,731,385,442,760,273,276,0.038776,0.045036,0.054251,0.062772,0.067467,0.113024,0.120153,0.127108,0.066945,0.076856,0.132151,0.047470,0.047992,True,5490,261,5710,41,0,0,0,0,0,0,2786
4,00610,26153,12678,13475,0.484763,0.515237,838,1369,1369,1513,1712,3353,3295,3688,1649,1944,3010,1952,461,0.032042,0.052346,0.052346,0.057852,0.065461,0.128207,0.125989,0.141016,0.063052,0.074332,0.115092,0.074638,0.017627,True,17937,8216,25053,920,116,0,0,0,43,21,12494

### 1.1. Number of lines Verification
The number of lines (one per zip code) in 2021 is different from 2011. Let's take a look at what is happening, how to move forward and what is the potential impact.

In [24]:
zip_list_21=c21['zip'].tolist()
zip_list_11=c11['zip'].tolist()

total_zips_11=c21['zip'].nunique()
total_zips_21=c11['zip'].nunique()


#what is in 21 that is not in 11:
out_of_list_11 = [item for item in zip_list_21 if item not in zip_list_11]
p_out_of_21=len(out_of_list_11)/total_zips_21*100
print('number of zips in 21 that are not in 11: ',len(out_of_list_11),'which represents: ','{:.2f}'.format(p_out_of_21),'% of total')

#what is in 11 that is not in 21:
out_of_list_21 = [item for item in zip_list_11 if item not in zip_list_21]
p_out_of_11=len(out_of_list_21)/total_zips_11*100
print('number of zips in 11 that are not in 21: ',len(out_of_list_21),'which represents: ', '{:.2f}'.format(p_out_of_11),'% of total')
#Let's see a few examples
#print(out_of_list_21)

number of zips in 21 that are not in 11:  851 which represents:  2.57 % of total
number of zips in 11 that are not in 21:  197 which represents:  0.58 % of total

In [25]:
zip_codes_missing_in_2011=c21[(c21['zip'].isin(out_of_list_11) )]
zip_codes_missing_in_2021=c11[(c11['zip'].isin(out_of_list_21) )]

### Reasons why some Zip codes are not present in both years
**Administrative Changes:** ZIP codes are not officially defined by the U.S. Census Bureau but are assigned by the United States Postal Service (USPS). Administrative changes, such as the creation, consolidation, or elimination of ZIP codes, may occur over time due to changes in postal delivery routes or administrative boundaries.

**Population Shifts:** Changes in population distribution and density within a region can influence the need for postal services and the assignment of ZIP codes. If the population in the area corresponding to ZIP code 04343 decreased significantly between 2011 and 2021, USPS might have adjusted postal delivery routes, resulting in the elimination of the ZIP code.

**Postal Service Updates:** The USPS regularly reviews and updates postal delivery routes to optimize efficiency and service coverage. This process may lead to changes in ZIP code boundaries or the elimination of less-used ZIP codes.

**Data Reporting:** Discrepancies in ZIP code data between censuses can also arise from differences in data collection methodologies, reporting practices, and data processing techniques used by the Census Bureau and other agencies.

## 2. Merge the 2 Dataframes

In [26]:
#Using outer to keep the zips that exist only in year but not in the other. For those there will be NaNs.
#Using the suffixes _21 and _11 to designate the respective years.
census=pd.merge(c21,c11,how='outer', on='zip', suffixes=('_21', '_11') )
census.shape

(33971, 87)

### 2.1. Reorder the merged fields

In [27]:
# I don't like the order. I will change it
l_c21=c21.columns.tolist()
l_c11=c11.columns.tolist()

#zip is the first and only common non duplicated field.
l_census = ['zip']
for item1, item2 in zip(l_c21[1:], l_c11[1:]):
    l_census.append(item1+'_21')
    l_census.append(item2+'_11')

# Print or use the combined list
print(l_census)
census=census[l_census]

['zip', 'total_pop_21', 'total_pop_11', 'male_pop_21', 'male_pop_11', 'female_pop_21', 'female_pop_11', 'male_ratio_21', 'male_ratio_11', 'female_ratio_21', 'female_ratio_11', 'age_under5_pop_21', 'age_under5_pop_11', 'age_5to9_pop_21', 'age_5to9_pop_11', 'age_10to14_pop_21', 'age_10to14_pop_11', 'age_15to19_pop_21', 'age_15to19_pop_11', 'age_20to24_pop_21', 'age_20to24_pop_11', 'age_25to34_pop_21', 'age_25to34_pop_11', 'age_35to44_pop_21', 'age_35to44_pop_11', 'age_45to54_pop_21', 'age_45to54_pop_11', 'age_55to59_pop_21', 'age_55to59_pop_11', 'age_60to64_pop_21', 'age_60to64_pop_11', 'age_65to74_pop_21', 'age_65to74_pop_11', 'age_75to84_pop_21', 'age_75to84_pop_11', 'age_85andOver_pop_21', 'age_85andOver_pop_11', 'age_under5_ratio_21', 'age_under5_ratio_11', 'age_5to9_ratio_21', 'age_5to9_ratio_11', 'age_10to14_ratio_21', 'age_10to14_ratio_11', 'age_15to19_ratio_21', 'age_15to19_ratio_11', 'age_20to24_ratio_21', 'age_20to24_ratio_11', 'age_25to34_ratio_21', 'age_25to34_ratio_11', 'age_35to44_ratio_21', 'age_35to44_ratio_11', 'age_45to54_ratio_21', 'age_45to54_ratio_11', 'age_55to59_ratio_21', 'age_55to59_ratio_11', 'age_60to64_ratio_21', 'age_60to64_ratio_11', 'age_65to74_ratio_21', 'age_65to74_ratio_11', 'age_75to84_ratio_21', 'age_75to84_ratio_11', 'age_85andOver_ratio_21', 'age_85andOver_ratio_11', 'age_group_outlier_21', 'age_group_outlier_11', 'race_one_21', 'race_one_11', 'race_two_or_more_21', 'race_two_or_more_11', 'race_hispanic_or_latino_21', 'race_hispanic_or_latino_11', 'race_white_alone_21', 'race_white_alone_11', 'race_black_or_african_21', 'race_black_or_african_11', 'race_american_indian_and_alaska_native_21', 'race_american_indian_and_alaska_native_11', 'race_asian_21', 'race_asian_11', 'race_native_hawaian_and_other_pacific_islander_21', 'race_native_hawaian_and_other_pacific_islander_11', 'race_some_other_race_alone_21', 'race_some_other_race_alone_11', 'race_two_or_more_races_21', 'race_two_or_more_races_11', 'total_housing_units_21', 'total_housing_units_11']

## 3. Calculate Deltas

In [28]:
census.head()
#First field is 'zip' and there is nothing to calculate for it.
all_common_fields=c21.columns.tolist()[1:]

print('BEFORE shape: ',census.shape)

for item in all_common_fields:
    column_21=item+'_21'
    column_11=item+'_11'
    new_column='delta_'+item
    #I don't have to worry about either columns containing nans because the result will be NaN and I can treat the result directly.
    census[new_column]=census[column_21]-census[column_11]
print('AFTER shape: ',census.shape)

l_census = ['zip']
for item in all_common_fields:
    column_21=item+'_21'
    column_11=item+'_11'
    new_column='delta_'+item
    l_census.append(column_21)
    l_census.append(column_11)
    l_census.append(new_column)

census=census[l_census]

BEFORE shape:  (33971, 87)
AFTER shape:  (33971, 130)

### 4. Save the Changes

In [29]:
#After all the changes, let's save in a csv file.

import os
outname = '2_Org_Census.csv'
outdir = '/Users/c32/Documents/NYCDSA/Projects/DATA/Ready_Data'
if not os.path.exists(outdir):
    os.mkdir(outdir)
fullname = os.path.join(outdir, outname)    

census.to_csv(fullname, header=True, index=False)
print("Saved!")

Saved!